# Generated by Django 2.1.7 on 2019-04-25 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, validators=[django.core.validators.EmailValidator(message='이메일 형식에 맞지 않습니다.')])),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(19, message='미성년자는 노노')])),
            ],
        ),
    ]
