# Generated by Django 2.1.7 on 2019-03-21 10:26

from django.db import migrations
import imagekit.models.fields
import votes.models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=votes.models.question_image_path),
        ),
    ]
