# Generated by Django 2.1.7 on 2019-03-21 10:28

from django.db import migrations
import imagekit.models.fields
import votes.models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0004_auto_20190321_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image_a',
            field=imagekit.models.fields.ProcessedImageField(upload_to=votes.models.question_image_path),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_b',
            field=imagekit.models.fields.ProcessedImageField(upload_to=votes.models.question_image_path),
        ),
    ]
